
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64  # Required for Apple Silicon
    container_name: ecommerce-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
    # This is volumen.
      - sqlserver_data:/var/opt/mssql

  app:
    build: .
    container_name: ecommerce-app
    ports:
      - "8000:8000"
    # environment:
    #   - DB_HOST=sqlserver
    #   - DB_SERVER=sqlserver
    #   - DB_DRIVER=pymssql
    depends_on:
      - sqlserver
    # This is bind mount.
    volumes:
      - ./app:/app/app

volumes:
  sqlserver_data:

networks:
  default:
    # external: true
    name: shared_network